### ISSUE TITLE
Feature request: Return color info on get transaction

### ISSUE THREAD

**Issue by dthorpe** [QBitNinja/QBitNinja#2]
It would be great if the qbit /transactions/<txid> returned colored asset information in the same manner that /wallets/<id>/balance and /balances/<addr> do.  Return color info if &colored=true

This would virtually eliminate the need for clients to use NBitcoin's expensive/exhaustive GetColoredTransaction() function at all, and save the clients from having to make dozens or hundreds of network calls to qbit /transaction to crawl the transaction chain in search of issuance txs.

**Comment by NicolasDorier** [comment]
very right, I don't know why I've not done it yet.
I think we talked about that, but I totally forgot.

**Comment by NicolasDorier** [comment]
Done 4496e39cfb58e87fb0e8aed3b678e364baff4c72 I updated client lib on nuget as well, I also added the "ReceivedCoins" property to the gettransaction response.
